name: "pv2mqtt"
version: "v0.0.7"
#image: "ghcr.io/martijnvds/ha-apps/pv2mqtt"
slug: "pv2mqtt"
description: "An MQTT Gateway for Solar Inverters, using SunSpec"
arch:
  - aarch64
  - amd64
services:
  - "mqtt:need"
init: false
apparmor: true
uart: true
startup: "services"
boot: "auto"
host_network: false
options:
  topic_prefix: "pv2mqtt"
  client_id: "pv2mqtt"
  connections:
    - name: "inverter1"
      type: "tcp"
      address: "192.168.1.10:502"
  devices:
    - connection: "inverter1"
      unit_id: 1
      interval: 30
schema:
  mqtt_url: str?
  client_id: str?
  topic_prefix: str
  connections:
    - name: str
      type: list(tcp|rtu)
      address: str?
      tls: bool?
      device: str?
      baud_rate: int?
      parity: match(none|even|odd)?
      keep_alive_interval: int?
  devices:
    - unit_id: int
      connection: str
      interval: int
